version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_WEBSOCKET_URL=${REACT_APP_WEBSOCKET_URL}
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true